// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file news.proto (package news.v1, syntax proto3)
/* eslint-disable */

//import "google/protobuf/struct.proto";

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file news.proto.
 */
export const file_news: GenFile = /*@__PURE__*/
  fileDesc("CgpuZXdzLnByb3RvEgduZXdzLnYxIlQKCU5ld3NFdmVudBIRCglzb3VyY2VfaWQYASABKAkSDQoFdGl0bGUYAiABKAkSDwoHY29udGVudBgDIAEoCRIUCgxwdWJsaXNoZWRfYXQYBCABKANiBnByb3RvMw");

/**
 * @generated from message news.v1.NewsEvent
 */
export type NewsEvent = Message<"news.v1.NewsEvent"> & {
  /**
   * референс на source id
   *
   * @generated from field: string source_id = 1;
   */
  sourceId: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string content = 3;
   */
  content: string;

  /**
   * @generated from field: int64 published_at = 4;
   */
  publishedAt: bigint;
};

/**
 * Describes the message news.v1.NewsEvent.
 * Use `create(NewsEventSchema)` to create a new message.
 */
export const NewsEventSchema: GenMessage<NewsEvent> = /*@__PURE__*/
  messageDesc(file_news, 0);

